FROM ubuntu:latest
LABEL name = "qark/ubuntu"

RUN apt update -y

RUN apt-get install -y python

RUN apt-get install -y python3-pip

RUN apt-get -y install openjdk-11-jre-headless

RUN pip3 install qark